### PR TITLE
Shutter this repository

### PR DESCRIPTION
**Pull request by whot**

### CODE REVIEW

**Comment by FFY00** [comment]
I mean, we can just archive it?

**Comment by whot** [comment]
the git repo remains anyway, so that's an archive by itself. and looking at the commits, I don't think there's any commit that removed or really changed stuff, so the bits moved to the wiki are the exact same data now.

**Comment by FFY00** [comment]
Archiving the repository just seems like a cleaner solution than deleting everything in a commit.

**Comment by whot** [comment]
well, I just learned that archiving a repository is a thing :)

but tbh, I don't know the benefit the archiving would bring over dropping everything and pointing the README to the other repository? Especially given that, like in our case, the changelog itself isn't particularly interesting and just the files themselves matter.

**Comment by bentiss** [comment]
I also think this PR makes more sense: we keep the webpage at http://libratbag.github.io/device-notes/ but have now just a linkto the libratbag wiki.

**Comment by FFY00** [comment]
I thought you could put that in the actual website repo but it's fine either way.

**Pull request merged**
